app/models/Estado.py
from app import db


class Estado(db.Model):
    __tablename__ = "estados"

    idEstado = db.Column(db.Integer, primary_key=True, autoincrement=True)
    descripcionEstado = db.Column(db.String(50), nullable=False)

app/routes/estado_routes.py
from flask import Blueprint, render_template, session, redirect, url_for, flash, request
from flask_login import login_required, current_user
from app.models.Estado import Estado
from app.decorators.admin_required import admin_required
from app.decorators.owner_required import owner_required
from app import db


bp = Blueprint("estado", __name__)


@bp.route("/Add/Estado", methods=["POST"])
@login_required
@admin_required
@owner_required
def add_estado():
    descripcionEstado = request.form["descripcionEstado"]

    new_estado = Estado(descripcionEstado=descripcionEstado)

    db.session.add(new_estado)
    db.session.commit()
    flash(["informacion", "Se añadio un nuevo estado"], "session")
    return redirect(url_for("administrador.view_complementos", tag="estado"))


@bp.route("/Delete/Estado/<int:estado>", methods=["POST"])
@login_required
@admin_required
@owner_required
def delete_estado(estado):

    estado = Estado.query.get_or_404(estado)
    db.session.delete(estado)

    db.session.commit()
    flash(["informacion", "Se elimino este estado"], "session")
    return redirect(url_for("administrador.view_complementos", tag="estado"))


@bp.route("/Edit/Estado/<int:estado>", methods=["POST"])
@login_required
@admin_required
@owner_required
def edit_estado(estado):

    estado = Estado.query.get_or_404(estado)
    estado.descripcionEstado = request.form['descripcionEstado']
    
    db.session.commit()
    
    flash(["informacion", "Se Actualizado este estado"], "session")
    return redirect(url_for("administrador.view_complementos", tag="estado"))

app/routes/rol_routes.py
from flask import Blueprint, render_template, session, redirect, url_for, flash, request
from flask_login import login_required, current_user
from app.models.Rol import Rol
from app.decorators.admin_required import admin_required
from app.decorators.owner_required import owner_required
from app import db


bp = Blueprint("rol", __name__)


@bp.route("/Add/Rol", methods=["POST"])
@login_required
@admin_required
@owner_required
def add_rol():
    descripcionRol = request.form["descripcionRol"]

    new_rol = Rol(descripcionRol=descripcionRol)

    db.session.add(new_rol)
    db.session.commit()
    flash(["informacion", "Se añadio un nuevo rol"], "session")
    return redirect(url_for("administrador.view_complementos", tag="rol"))


@bp.route("/Delete/Rol/<int:rol>", methods=["POST"])
@login_required
@admin_required
@owner_required
def delete_rol(rol):
    rol = Rol.query.get_or_404(rol)
    db.session.delete(rol)

    db.session.commit()
    flash(["informacion", "Se elimino este rol"], "session")
    return redirect(url_for("administrador.view_complementos", tag="rol"))


@bp.route("/Edit/Rol/<int:rol>", methods=["POST"])
@login_required
@admin_required
@owner_required
def edit_rol(rol):

    rol = Rol.query.get_or_404(rol)
    rol.descripcionRol = request.form['descripcionRol']
    
    db.session.commit()
    
    flash(["informacion", "Se Actualizado este rol"], "session")
    return redirect(url_for("administrador.view_complementos", tag="rol"))

app/routes/tipoDocumento_routes.py
from flask import Blueprint, render_template, session, redirect, url_for, flash, request
from flask_login import login_required, current_user
from app.models.TipoDocumento import TipoDocumento
from app.decorators.admin_required import admin_required
from app.decorators.owner_required import owner_required
from app import db


bp = Blueprint("tipoDocumento", __name__)


@bp.route("/Add/TipoDocumento", methods=["POST"])
@login_required
@admin_required
@owner_required
def add_tipoDocumento():
    descripcionTipoDocumento = request.form["descripcionTipoDocumento"]

    new_tipoDocumento = TipoDocumento(descripcionTipoDocumento=descripcionTipoDocumento)

    db.session.add(new_tipoDocumento)
    db.session.commit()
    flash(["informacion", "Se añadio un nuevo tipo de documento"], "session")
    return redirect(url_for("administrador.view_complementos", tag="tipoDocumento"))


@bp.route("/Delete/TipoDocumento/<int:tipoDocumento>", methods=["POST"])
@login_required
@admin_required
@owner_required
def delete_tipoDocumento(tipoDocumento):

    tipoDocumento = TipoDocumento.query.get_or_404(tipoDocumento)
    db.session.delete(tipoDocumento)

    db.session.commit()
    flash(["informacion", "Se elimino este tipo de documento"], "session")
    return redirect(url_for("administrador.view_complementos", tag="tipoDocumento"))


@bp.route("/Edit/TipoDocumento/<int:tipoDocumento>", methods=["POST"])
@login_required
@admin_required
@owner_required
def edit_tipoDocumento(tipoDocumento):

    tipoDocumento = TipoDocumento.query.get_or_404(tipoDocumento)
    tipoDocumento.descripcionTipoDocumento = request.form["descripcionTipoDocumento"]

    db.session.commit()

    flash(["informacion", "Se Actualizado este tipo de documento"], "session")
    return redirect(url_for("administrador.view_complementos", tag="tipoDocumento"))

app/templates/componentes/complementos/edit-tipoDocumento.html
<div class="overlay-editar">
    <div class="c_editar">

        <div class="c_cerrar">
            <div>
                <i data-name="cerrar" class="bi bi-x-lg"></i>
            </div>
        </div>
        <div class="c_titulo">
            <h3>Editar tipo de documento</h3>
        </div>
        <form action="{{ url_for('tipoDocumento.edit_tipoDocumento', tipoDocumento=tipoDocumento.idTipoDocumento) }}" method="POST" autocomplete="off">
            <div class="c_input">
                <input type="text" id="DescripcionTipoDocumento" name="descripcionTipoDocumento" value="{{ tipoDocumento.descripcionTipoDocumento }}"
                    placeholder="" required>
                <label for="DescripcionTipoDocumento">Decripción</label>
            </div>

            <div class="c_button">
                <button>
                    Actualizar
                    <i class="bi bi-pencil-square-fill"></i>
                </button>

                <button data-name="cerrar" type="button">Cancelar</button>
            </div>
        </form>

    </div>
</div>

app/templates/componentes/complementos/editar-estado.html
<div class="overlay-editar">
    <div class="c_editar">

        <div class="c_cerrar">
            <div>
                <i data-name="cerrar" class="bi bi-x-lg"></i>
            </div>
        </div>
        <div class="c_titulo">
            <h3>Editar estado</h3>
        </div>
        <form action="{{ url_for('estado.edit_estado', estado=estado.idEstado) }}" method="POST" autocomplete="off">
            <div class="c_input">
                <input type="text" id="DescripcionEstado" name="descripcionEstado" value="{{ estado.descripcionEstado }}"
                    placeholder="" required>
                <label for="DescripcionEstado">Decripción</label>
            </div>

            <div class="c_button">
                <button>
                    Actualizar
                    <i class="bi bi-pencil-square-fill"></i>
                </button>

                <button data-name="cerrar" type="button">Cancelar</button>
            </div>
        </form>

    </div>
</div>

app/templates/componentes/complementos/editar-rol.html
<div class="overlay-editar">
    <div class="c_editar">

        <div class="c_cerrar">
            <div>
                <i data-name="cerrar" class="bi bi-x-lg"></i>
            </div>
        </div>
        <div class="c_titulo">
            <h3>Editar rol</h3>
        </div>
        <form action="{{ url_for('rol.edit_rol', rol=rol.idRol) }}" method="POST" autocomplete="off">
            <div class="c_input">
                <input type="text" id="DescripcionRol" name="descripcionRol" value="{{ rol.descripcionRol }}"
                    placeholder="" required>
                <label for="DescripcionRol">Decripción</label>
            </div>

            <div class="c_button">
                <button>
                    Actualizar
                    <i class="bi bi-pencil-square-fill"></i>
                </button>

                <button data-name="cerrar" type="button">Cancelar</button>
            </div>
        </form>

    </div>
</div>

app/templates/componentes/complementos/estados.html
<div class="c_form">
    <div class="c_titulo">
        <h3>Agregar estados</h3>
    </div>
    <form action="{{ url_for('estado.add_estado') }}" method="POST" autocomplete="off">
        <div class="c_input">
            <input type="text" id="DescripcionEstado" name="descripcionEstado" placeholder="" required>
            <label for="DescripcionEstado">Decripción</label>
        </div>

        <div class="c_button">
            <button id="BTNAgregarEstado">
                Registrar
                <i class="bi bi-plus-square"></i>
            </button>
        </div>
    </form>
</div>
<div class="c_table">
    <table id="TablaEstados">
        <thead>
            <tr>
                <th>Id</th>
                <th>Descripción</th>
            </tr>
        </thead>
        <tbody>
            {% for estado in estados %}
            <tr>
                <td>{{ estado.idEstado }}</td>
                <td>{{ estado.descripcionEstado }}</td>
                <td>
                    <a>
                        <i class="bi bi-pencil-square"></i>
                        {% include 'componentes/complementos/editar-estado.html' %}
                    </a>
                </td>
                <td>
                    <form action="{{ url_for('estado.delete_estado', estado=estado.idEstado) }}" method="POST">
                        <button><i class="bi bi-trash3"></i></button>
                    </form>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

app/templates/componentes/complementos/roles.html
<div class="c_form">
    <div class="c_titulo">
        <h3>Agregar roles</h3>
    </div>
    <form action="{{ url_for('rol.add_rol') }}" method="POST" autocomplete="off">
        <div class="c_input">
            <input type="text" id="DescripcionRol" name="descripcionRol" placeholder="" required>
            <label for="DescripcionRol">Decripción</label>
        </div>

        <div class="c_button">
            <button id="BTNAgregarrRol">
                Registrar
                <i class="bi bi-plus-square"></i>
            </button>
        </div>
    </form>
</div>
<div class="c_table">
    <table id="TablaRoles">
        <thead>
            <tr>
                <th>Id</th>
                <th>Descripción</th>
            </tr>
        </thead>
        <tbody>
            {% for rol in roles %}
            <tr>
                <td>{{ rol.idRol }}</td>
                <td>{{ rol.descripcionRol }}</td>
                <td>
                    <a>
                        <i class="bi bi-pencil-square"></i>
                        {% include 'componentes/complementos/editar-rol.html' %}
                    </a>
                </td>
                <td>
                    <form action="{{ url_for('rol.delete_rol', rol=rol.idRol) }}" method="POST">
                        <button><i class="bi bi-trash3"></i></button>
                    </form>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

app/templates/componentes/complementos/tiposDocumento.html
<div class="c_form">
    <div class="c_titulo">
        <h3>Agregar tipos de documento</h3>
    </div>
    <form action="{{ url_for('tipoDocumento.add_tipoDocumento') }}" method="POST" autocomplete="off">
        <div class="c_input">
            <input type="text" id="DescripcionTipoDocumento" name="descripcionTipoDocumento" placeholder="" required>
            <label for="DescripcionTipoDocumento">Decripción</label>
        </div>

        <div class="c_button">
            <button id="BTNAgregarEstado">
                Agregar
                <i class="bi bi-plus-square"></i>
            </button>
        </div>
    </form>
</div>
<div class="c_table">
    <table id="TablaEstados">
        <thead>
            <tr>
                <th>Id</th>
                <th>Descripción</th>
            </tr>
        </thead>
        <tbody>
            {% for tipoDocumento in tiposDocumento %}
            <tr>
                <td>{{ tipoDocumento.idTipoDocumento }}</td>
                <td>{{ tipoDocumento.descripcionTipoDocumento }}</td>
                <td>
                    <a>
                        <i class="bi bi-pencil-square"></i>
                        {% include 'componentes/complementos/edit-tipoDocumento.html' %}
                    </a>
                </td>
                <td>
                    <form
                        action="{{ url_for('tipoDocumento.delete_tipoDocumento', tipoDocumento=tipoDocumento.idTipoDocumento) }}"
                        method="POST">
                        <button>
                            <i class="bi bi-trash3"></i>
                        </button>
                    </form>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>