app/models/Usuario.py
from app import db
from flask_login import UserMixin
from sqlalchemy import UniqueConstraint


class Usuario(db.Model, UserMixin):
    __tablename__ = "usuarios"

    idUsuario = db.Column(db.Integer, primary_key=True, autoincrement=True)
    nombreUsuario = db.Column(db.String(50), nullable=False)
    apellidoUsuario = db.Column(db.String(50), nullable=False)
    idTipoDocumento = db.Column(
        db.Integer, db.ForeignKey("tiposdocumento.idTipoDocumento"), nullable=False
    )
    tipoDocumentoUsuario = db.relationship("TipoDocumento")
    documentoUsuario = db.Column(db.String(30), nullable=False, unique=True)
    correoUsuario = db.Column(db.String(56), nullable=False, unique=True)
    telefonoUsuario = db.Column(db.String(60))
    idRol = db.Column(
        db.Integer, db.ForeignKey("roles.idRol"), nullable=False, default=1
    )
    rolUsuario = db.relationship("Rol")
    descripcionUsuario = db.Column(db.String(255))
    fotoUsuario = db.Column(db.String(60))
    idEstado = db.Column(
        db.Integer, db.ForeignKey("estados.idEstado"), nullable=False, default=1
    )
    estadoUsuario = db.relationship("Estado")
    idVoto = db.Column(db.Integer, db.ForeignKey("usuarios.idUsuario"))
    votoUsuario = db.relationship("Usuario", remote_side=[idUsuario])
    contraseniaUsuario = db.Column(db.VARBINARY(256))
    codigoUsuario = db.Column(db.String(10))


    def get_id(self):
        return self.idUsuario

app/routes/usuario_routes.py
from flask import Blueprint, render_template, request, redirect, url_for, flash
from flask_login import login_required, logout_user, login_user, current_user
from flask import Blueprint, render_template
from sqlalchemy.orm import aliased
from sqlalchemy import not_, asc, desc
import random, os, bcrypt
import smtplib
from dotenv import load_dotenv
from datetime import datetime
import matplotlib.pyplot as plt
from io import BytesIO
import base64
from email.mime.text import MIMEText
from email.mime.image import MIMEImage
from email.mime.multipart import MIMEMultipart
from app.models.Usuario import Usuario
from app.models.Votacion import Votacion
from app import db

bp = Blueprint("usuario", __name__)


@bp.route("/Profile", methods=["GET"])
@login_required
def view_profile():
    ultimaVotacion = Votacion.query.order_by(desc(Votacion.idVotacion)).first()
    return render_template("usuario/profile-user.html", votacion=ultimaVotacion)


@bp.route("/Home")
@login_required
def view_home():
    ultimaVotacion = Votacion.query.order_by(desc(Votacion.idVotacion)).first()
    return render_template("usuario/index.html", votacion=ultimaVotacion)


@bp.route("/Vote")
@login_required
def view_vote():
    ultimaVotacion = Votacion.query.order_by(desc(Votacion.idVotacion)).first()  
    candidatos = Usuario.query.filter_by(idRol=2).all()
    return render_template(
        "usuario/vote.html", candidatos=candidatos, votacion=ultimaVotacion
    )


@bp.route("/Results")
@login_required
def view_results():
    usuario_alias = aliased(Usuario)
    votos = dict(
        (
            db.session.query(usuario_alias.nombreUsuario, db.func.count(Usuario.idVoto))
            .join(usuario_alias, Usuario.idVoto == usuario_alias.idUsuario)
            .filter(Usuario.idVoto.isnot(None))
            .group_by(usuario_alias.nombreUsuario)
            .all()
        )
    )

    anio = ""
    ultimaVotacion = Votacion.query.order_by(desc(Votacion.idVotacion)).first()
    if ultimaVotacion:
        anio = ultimaVotacion.fechaInicioVotacion.year

    # grafico = get_graphic(votos, anio=anio)

    return render_template(
        "usuario/results-votes.html", votacion=ultimaVotacion
    )


@bp.route("/save-vote", methods=["POST"])
def vote():
    candidato = request.form["candidatoUsuario"]
    usuario = Usuario.query.get_or_404(current_user.idUsuario)
    usuario.voto = candidato
    db.session.commit()
    flash(["informacion", "Voto registrado con exito"], "session")
    return redirect(url_for("usuario.view_home"))


@bp.route("/edit-profile/", methods=["POST"])
@login_required
def edit_profile():
    usuario = Usuario.query.get_or_404(current_user.idUsuario)
    usuario.nombreUsuario = request.form.get("nombreUsuario", usuario.nombreUsuario)
    usuario.apellidoUsuario = request.form.get(
        "apellidoUsuario", usuario.apellidoUsuario
    )
    usuario.documentoUsuario = request.form.get(
        "documentoUsuario", usuario.documentoUsuario
    )
    usuario.correoUsuario = request.form.get("correoUsuario", usuario.correoUsuario)
    usuario.telefonoUsuario = request.form.get(
        "telefonoUsuario", usuario.telefonoUsuario
    )
    usuario.descripcionUsuario = request.form.get(
        "descripcionUsuario", usuario.descripcionUsuario
    )

    if "fotoUsuario" in request.files:
        foto = request.files["fotoUsuario"]
        if foto.filename != "":
            delete_user_photo(current_user.idUsuario)
            usuario.fotoUsuario = name_user_photo(usuario, foto.filename)
            save_user_photo(foto, usuario)

    if "contraseniaOldUsuario" in request.form and "contraseniaUsuario" in request.form:
        c_old = request.form["contraseniaOldUsuario"]
        c_nueva = request.form["contraseniaUsuario"]

        if len(c_nueva) < 8:
            error = [
                "contraseniaUsuario",
                "La contraseña debe tener mínimo 8 caracteres",
            ]
            flash(error, "session")
            return redirect(url_for("usuario.view_profile"))

        if c_old and c_nueva:
            if not bcrypt.checkpw(c_old.encode("utf-8"), usuario.contraseniaUsuario):
                flash(["error", "Algunos datos son invalidos"], "session")
                return redirect(url_for("usuario.view_profile"))

            usuario.contraseniaUsuario = bcrypt.hashpw(
                c_nueva.encode("utf-8"), bcrypt.gensalt()
            )

    db.session.commit()
    flash(["informacion", "Perfil actualizado"], "session")
    return redirect(url_for("administrador.view_home"))


@bp.route("/Search/Apprentice", methods=["POST"])
def search_apprentice():
    
    data = request.json
    documentoUsuario = data["documentoUsuario"]

    usuario = (
        Usuario.query.filter_by(documentoUsuario=documentoUsuario)
        .filter(~Usuario.idRol.in_([3, 4]))
        .first()
    )

    if not usuario:
        return {"rs": 404}

    descripcionUsuarioV = (
        True
        if usuario.descripcionUsuario is not None and usuario.descripcionUsuario.strip() != ""
        else False
    )
    fotoUsuarioV = True if usuario.fotoUsuario and usuario.fotoUsuario != "" else False
    estadoUsuarioV = True if usuario.idEstado == 1 else False

    valido = True if descripcionUsuarioV and fotoUsuarioV and estadoUsuarioV else False

    usuario = {
        "idUsuario": usuario.idUsuario,
        "nombreUsuario": usuario.nombreUsuario,
        "usuarioValido": valido,
        "rolUsuario": usuario.rolUsuario.descripcionRol,
        "fotoUsuario": fotoUsuarioV,
        "descripcionUsuario": descripcionUsuarioV,
        "estadoUsuarioV": estadoUsuarioV,
        "estadoUsuario": usuario.estadoUsuario.descripcionEstado,
    }
    return {"rs": 304, "usuario": usuario}


@bp.route("/search/user", methods=["POST"])
def search_user():

    data = request.json
    documentoUsuario = data["documentoUsuario"]

    usuario = Usuario.query.filter_by(documentoUsuario=documentoUsuario).first()

    if not usuario:
        return {"rs": 404}

    rs = {"rs": 200, "idUsuario": usuario.idUsuario}

    return rs


@bp.route("/add/Candidate/<int:usuario>", methods=["POST"])
def add_candidate(usuario):
    usuario = Usuario.query.get_or_404(usuario)
    usuario.idRol = 2
    db.session.commit()

    flash(["informacion", "El aprendiz ahora es candidato"], "session")
    return redirect(url_for("administrador.view_home"))


@bp.route("/Send-suggestion", methods=["POST"])
def send_suggestion():

    data = request.json
    correo = data["correo"]
    mensaje = data["mensaje"]
    nombre = data["nombre"]

    fecha = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    mensaje += f"""
    
    Envía:
    {correo}
    {nombre}
    {fecha}"""
    try:
        send_mail(
            asunto="Sugerencias",
            destinatario="cfmorales.diaz20@gmail.com",
            finalMensaje="tu sugerencia",
            contenido=mensaje,
        )
    except Exception:
        return "500"

    return "200"


@bp.route("/edit/user/<int:usuario>", methods=["POST"])
def edit_user(usuario):
    usuario = Usuario.query.get_or_404(usuario)

    nombreUsuario = request.form["nombreUsuario"]
    apellidoUsuario = request.form["apellidoUsuario"]
    idTipoDocumento = request.form["tipoDocumentoUsuario"]
    usuario.nombreUsuario = nombreUsuario
    usuario.apellidoUsuario = apellidoUsuario
    usuario.idTipoDocumento = idTipoDocumento
    db.session.commit()

    flash(["informacion", "Se edito el usuario"], "session")
    return redirect(url_for("administrador.view_usuario"))

@bp.route("/Restablecer/Contraseña/<int:usuario>", methods=["POST"])
def reset_password(usuario):
    usuario = Usuario.query.get_or_404(usuario)
    contraseniaUsuario = request.form['contraseniaUsuario'].encode('utf-8')
    usuario.contraseniaUsuario = bcrypt.hashpw(password=contraseniaUsuario, salt=bcrypt.gensalt())
    usuario.codigoUsuario = None
    
    db.session.commit()
    flash(['informacion', 'Tu contraseña se cambió. Ya puedes iniciar sesión'], 'session')
    return redirect(url_for('auth.view_login'))
    
# //////////////////////////////////////////////
# Funciones


def save_user_photo(file, usuario):
    from run import app

    filename = file.filename
    destination_folder = os.path.join(app.root_path, "static", "images")
    file.save(
        os.path.join(
            destination_folder, name_user_photo(usuario=usuario, filename=filename)
        )
    )


def name_user_photo(usuario, filename):
    formato = os.path.splitext(filename)[1]
    name = f"perfil_{usuario.nombreUsuario}{formato}"
    return name


def delete_user_photo(idUsuario):
    from run import app
    fotoUsuario = Usuario.query.get_or_404(idUsuario).fotoUsuario
    if fotoUsuario:
        ruta_imagen = os.path.join(app.root_path, "static", "images", fotoUsuario)
        if os.path.exists(ruta_imagen):
            os.remove(ruta_imagen)


def send_mail(asunto, destinatario, contenido, finalMensaje, tipoContenido="plain"):
    load_dotenv()

    smtp_user = os.getenv("smtp_user")
    smtp_password = os.getenv("smtp_password")
    smtp_host = os.getenv("smtp_host")
    smtp_port = os.getenv("smtp_port")
    smtp_name = os.getenv("smtp_name")

    mensaje = MIMEMultipart()

    mensaje["From"] = smtp_name
    mensaje["To"] = destinatario

    mensaje["Subject"] = asunto
    mensaje.attach(MIMEText(contenido, tipoContenido))
    
    try:
        with smtplib.SMTP(smtp_host, smtp_port) as servidor_smtp:
            servidor_smtp.starttls()
            servidor_smtp.login(smtp_user, smtp_password)
            servidor_smtp.sendmail(from_addr=smtp_user, to_addrs=destinatario, msg=mensaje.as_string())
            return {
                "rs": 200,
                "msj": f"Se ha enviado {finalMensaje}",
            }
    except Exception as ex:
        return {
            "rs": 500,
            "msj": "Ocurrio un error al procesar la peticion, intentalo más tarde"
            + str(ex),
        }

app/templates/usuario/profile-user.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{{ url_for('static', filename='css/perfil.css') }}" />
    <script src="{{ url_for('static', filename='js/perfil.js') }}" defer></script>
    <link rel="icon" href="{{ url_for('static', filename='images/favicon.ico') }}" />
    <link rel="stylesheet" href="{{ url_for('static', filename='css/icons/bootstrap-icons.css') }}">
    <title>Votaciones - Profile</title>
</head>

<body>
    <main>
        {% if current_user.idRol == 3 or current_user.idRol == 4 %} {%
        include 'componentes/header-administrador.html' %} {% else %} {%
        include 'componentes/header.html' %} {% endif %}

        <div class="c_form">
            <form autocomplete="off" action="{{ url_for('usuario.edit_profile') }}" method="post"
                enctype="multipart/form-data">
                <div class="datos-basicos">
                    <div class="titulo">
                        <h2>
                            Datos Basicos
                            <div class="c_editar">
                                <i class="bi bi-pencil-square" title="Editar Perfil" id="EditarPerfil"></i>
                                <div class="msg_editar-perfil">
                                    <div class="arrow-left"></div>
                                    <div class="contenido">Editar Perfil</div>
                                </div>
                            </div>
                        </h2>
                    </div>
                    <div class="fields">
                        <div class="c_input">
                            <input name="nombreUsuario" id="NombreUsuario" type="text"
                                value="{{ current_user.nombreUsuario }}" placeholder="" required disabled />
                            <label for="NombreUsuario">Nombre</label>
                        </div>
                        <div class="c_input">
                            <input name="apellidoUsuario" id="ApellidoUsuario" type="text"
                                value="{{ current_user.apellidoUsuario }}" placeholder="" required disabled />
                            <label for="ApellidoUsuario">Apellido</label>
                        </div>
                        <div class="c_select">
                            <select name="tipoDocumentoUsuario" id="TipoDocumentoUsuario" disabled>
                                <option value="{{ current_user.idTipoDocumento }}" selected>
                                    {{
                                    current_user.tipoDocumentoUsuario.descripcionTipoDocumento
                                    }}
                                </option>

                                {% for tipoDocumento in TiposDocumento %} {%
                                if current_user.idTipoDocumento !=
                                tipoDocumento.idTipoDocumento %}
                                <option value="{{ tipoDocumento.idTipoDocumento }}">
                                    {{
                                    tipoDocumento.descripcionTipoDocumento
                                    }}
                                </option>
                                {% endif %} {% endfor %}
                            </select>
                            <label for="TipoDocumentoUsuario">Tipo de documento</label>
                        </div>
                        <div class="c_select">
                            <select name="rolusuario" id="RolUsuario" disabled>
                                <option value="{{ current_user.idRol }}" selected>
                                    {{
                                    current_user.rolUsuario.descripcionRol
                                    }}
                                </option>
                            </select>
                            <label for="RolUsuario">Rol</label>
                        </div>
                        <div class="c_input">
                            <input name="documentoUsuario" id="DocumentoUsuario" type="number"
                                value="{{ current_user.documentoUsuario }}" placeholder="" required disabled />
                            <label for="DocumentoUsuario">Documento</label>
                        </div>
                        <div class="c_input">
                            <input name="correoUsuario" id="CorreoUsuario" type="email"
                                value="{{ current_user.correoUsuario }}" placeholder="" required disabled />
                            <label for="CorreoUsuario">Correo</label>
                        </div>
                        <div class="c_input last">
                            <input name="telefonoUsuario" id="TelefonoUsuario" type="number"
                                value="{{ current_user.telefonoUsuario }}" placeholder="" disabled />
                            <label disabled for="TelefonoUsuario">Telefono</label>
                        </div>
                        <div class="c_acciones" id="Acciones" editar="false">
                            <input type="checkbox" name="" id="EditarContraseñas" disabled>
                            <label for="EditarContraseñas">Cambiar contraseña</label>
                        </div>
                        <div class="c_input" id="ContraseniaOld" editar="false">
                            <input name="contraseniaOldUsuario" id="OldPaswordUsuario" type="password" value=""
                                placeholder="" required disabled />
                            <label for="OldPaswordUsuario">Contraseña actual</label>
                        </div>
                        <div class="c_input" id="NuevaContrasenia" editar="false">
                            <input name="contraseniaUsuario" id="ContraseniaUsuario" type="password" value=""
                                placeholder="" required disabled />
                            <label for="ContraseniaUsuario">Nueva contraseña</label>
                        </div>
                        <div class="c_button" id="BTNActualizar" editar="false">
                            <button type="submit" name="" id="buttonRegistrar">
                                Actualizar datos
                            </button>
                        </div>
                    </div>
                </div>
                <div class="datos-opcionales">
                    <div class="c_foto-perfil">
                        <div class="foto">
                            <img src="{{ url_for('static', filename='images/' ~ (current_user.fotoUsuario if current_user.fotousuario and current_user.fotousuario != '' else 'Triste!.jpg')) }}"
                                alt="Foto de {{ current_user.nombreUsuario }}" id="imgFotoUsuario">
                            <div class="c_overlay" id="Overlay-foto">
                                <div class="c_icono">
                                    <i class="bi bi-camera-fill"></i>
                                </div>
                                <div class="c_texto">
                                    Cambiar foto de perfil
                                </div>
                            </div>
                        </div>
                        <div class="c_input-file">
                            <input type="file" name="fotoUsuario" id="FotoUsuario" accept=".png, .jpg, .gif, .jpeg"
                                disabled />
                        </div>
                        <div class="nombre-archivo">
                            <label id="Nombre-archivo" for="FotoUsuario">Seleccionar archivo</label>
                        </div>
                        <div class="fields c_descripcion">
                            <div class="c_input">
                                <textarea name="descripcionUsuario" id="DescripcionUsuario" placeholder=""
                                    maxlength="100"
                                    disabled>{{ current_user.descripcionUsuario if current_user.descripcionUsuario else '' }}</textarea>
                                <label for="DescripcionUsuario">Descripción</label>
                            </div>
                        </div>
                    </div>
            </form>
        </div>
        {% include 'componentes/alerta.html' %}
    </main>
</body>

</html>

app/templates/usuario/results-votes.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="{{ url_for('static', filename='css/resultados-votacion.css') }}" />
    <script src="{{ url_for('static', filename='js/resultados-votacion.js') }}"></script>
    <link rel="icon" href="{{ url_for('static', filename='images/favicon.ico') }}" />
    <title>Votaciones - Resultados</title>
</head>

<body>
    <main class="{{ 'mensaje' if votacion.estadoVotacion != 5 else '' }}">
        {% include 'componentes/header.html' %} {% if
        votacion.idEstado == 3 %}

        <div class="c_ganador">
            <div class="c_foto">
                <img src="{{ url_for('static', filename='images/' ~ (votacion.ganador.fotoUsuario if votacion.ganadorVotacion.fotoUsuario else 'Triste!.jpg')) }}"
                    alt="{{ votacion.ganadorVotacion.nombreUsuario }}" />
            </div>
            <div class="c_datos">
                <div class="candidato">
                    <h3>
                        {{ votacion.ganadorVotacion.nombreUsuario }} {{
                        votacion.idGanador.apellidoUsuario }}
                    </h3>
                    <div class="separador horizontal"></div>
                    <p>{{ votacion.ganadorVotacion.correoUsuario }}</p>
                    <p>{{ votacion.ganadorVotacion.descripcionUsuario if votacion.ganadorVotacion.descripcionUsuario is
                        not none and votacion.ganadorVotacion.descripcionUsuario != '' else 'Sin descripción' }}
                    </p>
                </div>

                <div class="separador horizontal"></div>

                <div class="votacion">
                    <h5>
                        Votos obtenidos:
                        <b>{{ votacion.totalVotosVotacion }}</b>
                    </h5>
                    <h5>
                        Porcentaje obtenido:
                        <b>{{ votacion.porcentajeVotosVotacion }}%</b>
                    </h5>
                </div>
            </div>
        </div>
        <div class="c_grafico">
            <!-- <img src="data:image/png;base64,{{ graficoVotos }}" alt="Gráfico de Votos" /> -->
            <img src="{{ url_for('static', filename='images/resultados.png') }}" alt="">
        </div>

        {% else %}

        <div class="c_mensaje">
            <h3>Aun no ha finalizado la votacion</h3>
            <p>
                Te avisaremos al finalizar para que revises los resultados
            </p>
        </div>

        {% endif %}
    </main>
</body>

</html>

app/templates/usuario/vote.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="icon" href="{{ url_for('static', filename='images/favicon.ico') }}" />
    <link rel="stylesheet" href="{{ url_for('static', filename='css/votar.css') }}" />
    <link rel="stylesheet" href="{{ url_for('static', filename='css/icons/bootstrap-icons.css') }}" />
    <script src="{{ url_for('static', filename='js/votar.js') }}" defer></script>
    <title>Votaciones - Votar</title>
</head>

<body>
    <main>
        {% include 'componentes/header.html' %}
        <span class="separador horizontal"></span>
        <div class="c_title">
            <h1>Candidatos</h1>
        </div>
        <span class="separador horizontal"></span>
        {% if candidatos|length > 1 and votacion.idEstado == 1 %}
        <form action="{{ url_for('usuario.vote') }}" method="POST">
            <div class="c_candidatos">
                {% for candidato in candidatos %} {% if not
                candidato.idCandidato == 15 %}
                <div id="card-candidato">
                    <div class="card-candidato">
                        <div class="c_nombre-candidato">
                            <h3 title="Click para ver más información">
                                {{ candidato.nombreUsuario }}
                            </h3>
                        </div>
                        <div title="Click para ver más información" class="c_foto-candidato">
                            <img src="{{ url_for('static', filename='images/' ~ candidato.fotoUsuario) }}"
                                alt="Foto de {{ candidato.nombreUsuario}}" />
                        </div>
                        <div class="seleccionar-candidato">
                            <div class="c_input-checkbox">
                                <input name="candidatoUsuario" value="{{ candidato.idUsuario }}"
                                    id="s_candidato-{{ candidato.idUsuario }}" type="radio" />
                                <label seleccionado="false" for="s_candidato-{{ candidato.idUsuario }}"></label>
                            </div>
                        </div>
                    </div>

                    <div class="c_informacion-candidato">
                        <div class="informacion-candidato">
                            <a class="cerrar">
                                <i class="bi bi-x"></i>
                            </a>
                            <div class="c_nombre">
                                <h3>
                                    {{ candidato.nombreUsuario }} {{
                                    candidato.apellidoUsuario }}
                                </h3>
                            </div>
                            <div class="informacion">
                                <img src="{{ url_for('static', filename='images/' ~ candidato.fotoUsuario) }}"
                                    alt="Foto de {{ candidato.nombreUsuario }}" />
                                <p>
                                    {% if candidato.descripcionUsuario !=
                                    'None' %} {{
                                    candidato.descripcionUsuario }} {% else
                                    %} Sin descripción {% endif %}
                                </p>
                            </div>
                            <div class="c_button">
                                <button>Cerrar</button>
                            </div>
                        </div>
                    </div>
                </div>
                {% endif %} {% endfor %} {% for candidato in candidatos %}
                {% if candidato.idCandidato == 15 %}
                <div id="card-candidato">
                    <div class="card-candidato">
                        <div class="c_nombre-candidato">
                            <h3>{{ candidato.nombreUsuario }}</h3>
                        </div>
                        <div class="c_foto-candidato">
                            <img src="{{ url_for('static', filename='images/' ~ candidato.fotoUsuario) }}"
                                alt="Foto de {{ candidato.nombreUsuario }}" />
                        </div>
                        <div class="seleccionar-candidato">
                            <div class="c_input-checkbox">
                                <input name="candidatoUsuario" value="{{ candidato.idUsuario }}"
                                    id="s_candidato-{{ candidato.idUsuario }}" type="radio" />
                                <label seleccionado="false" for="s_candidato-{{ candidato.idUsuario }}"></label>
                            </div>
                        </div>
                    </div>
                </div>
                {% endif %} {% endfor %}
            </div>
            {% if current_user.rolUsuario.idRol == 1 %}
            <div class="c_button">
                <button id="BTNVotar">Votar</button>
            </div>
            {% endif %}{% if current_user.rolUsuario.idRol >= 4 %}
            <div class="c_mensaje error">
                <p>Los administradores no pueden votar</p>
            </div>
            {% endif %}
        </form>
        {% endif %} {% if candidatos|length <= 1 or votacion.idEstado != 1 %} <div class="c_noCandidatos">
            <h2>No disponible</h2>
            <p>Aun no hay canditos para elegir</p>
            <p>o no hay votaciones activas</p>
            </div>
            {% endif %}{% include 'componentes/alerta.html' %}
    </main>
</body>

</html>