app/routes/administrador_routes.py
from flask import Blueprint, render_template, session, redirect, url_for, flash, request
from sqlalchemy import desc
from flask_login import login_required, current_user
from app.models.TipoDocumento import TipoDocumento
from app.models.Usuario import Usuario
from app.models.Votacion import Votacion
from app.models.Estado import Estado
from app.models.Rol import Rol
from app.decorators.admin_required import admin_required
from app.decorators.owner_required import owner_required
from app import db
import json

bp = Blueprint("administrador", __name__)


@bp.route("/Administrar")
@login_required
@admin_required
def view_home():
    config = carga_config()
    usuarios = Usuario.query.filter(~Usuario.idRol.in_([3, 4])).all()
    return render_template("administrador/index.html", usuarios=usuarios, config=config)


@bp.route("/Votaciones")
@login_required
@admin_required
def view_votes():
    usuarios = Usuario.query.filter(~Usuario.idRol.in_([3, 4])).all()
    votaciones = Votacion.query.order_by(desc(Votacion.idVotacion)).all()
    rpActual = Votacion.query.order_by(desc(Votacion.idVotacion)).first()
    config = carga_config()

    return render_template(
        "administrador/votes.html",
        votaciones=votaciones,
        rpActual=rpActual,
        usuarios=usuarios,
        config=config,
    )


@bp.route("/Aprendices")
@login_required
@admin_required
def view_aprendices():
    aprendices = Usuario.query.filter_by(idRol=1).all()
    usuariosAll = Usuario.query.filter(~Usuario.idRol.in_([3, 4])).all()
    tiposDocumento = TipoDocumento.query.all()
    config = carga_config()

    return render_template(
        "administrador/aprendices.html",
        aprendices=aprendices,
        usuariosAll=usuariosAll,
        tiposDocumento=tiposDocumento,
        config=config,
    )


@bp.route("/Usuarios")
@login_required
@admin_required
@owner_required
def view_usuarios():
    usuarios = Usuario.query.filter(~Usuario.idRol.in_([3, 4])).all()
    usuariosAll = Usuario.query.filter(~Usuario.idRol.in_([4])).all()
    tiposDocumento = TipoDocumento.query.all()
    config = carga_config()

    return render_template(
        "administrador/usuarios.html",
        usuarios=usuarios,
        usuariosAll=usuariosAll,
        tiposDocumento=tiposDocumento,
        config=config,
    )


@bp.route("/Complementos")
@login_required
@admin_required
@owner_required
def view_complementos():
    usuarios = Usuario.query.filter(~Usuario.idRol.in_([3, 4])).all()
    estados = Estado.query.all()
    tiposDocumento = TipoDocumento.query.all()
    roles = Rol.query.all()
    config = carga_config()

    return render_template(
        "administrador/complementos.html",
        usuarios=usuarios,
        estados=estados,
        tiposDocumento=tiposDocumento,
        roles=roles,
        config=config,
    )


@bp.route("/add/admin/<int:usuario>", methods=["POST"])
@login_required
@admin_required
@owner_required
def add_admin(usuario):
    usuario = Usuario.query.get_or_404(usuario)
    usuario.idRol = 3
    db.session.commit()
    flash(["informacion", "El usuario ahora es administrador"], "session")
    return redirect(url_for("administrador.view_usuarios"))


@bp.route("/remove/admin/<int:usuario>", methods=["POST"])
@login_required
@admin_required
@owner_required
def remove_admin(usuario):
    usuario = Usuario.query.get_or_404(usuario)
    usuario.idRol = 1
    db.session.commit()

    flash(["informacion", "El usuario ya no es administrador"], "session")
    return redirect(url_for("administrador.view_usuarios"))


@bp.route("/Edit/Config/", methods=["POST"])
@login_required
@admin_required
@owner_required
def edit_config():

    correosInicioVotacion = request.form.get("correosInicioVotacion", "off")
    correosFinVotacion = request.form.get("correosFinVotacion", "off")
    correosSancionesVotacion = request.form.get("correosSancionesVotacion", "off")

    correosInicioVotacion = True if correosInicioVotacion == "on" else False
    correosFinVotacion = True if correosFinVotacion == "on" else False
    correosSancionesVotacion = True if correosSancionesVotacion == "on" else False

    config = carga_config()

    nueva_config = {
        "correosInicioVotacion": correosInicioVotacion,
        "correosFinVotacion": correosFinVotacion,
        "correosSancionesVotacion": correosSancionesVotacion,
    }

    config.update(nueva_config)

    with open("config.json", "w") as f:
        json.dump(config, f, indent=4)
    

    flash(["informacion", "La configuraciones se actualizaron correctamente"], "session")
    return redirect(url_for('administrador.view_home'))


def carga_config():
    with open("config.json") as f:
        config = json.load(f)
        return config

app/routes/auth_routes.py
from app import db
from flask import Blueprint, render_template, request, redirect, url_for, flash
from flask_login import login_required, logout_user, login_user, current_user
from flask import Blueprint, render_template
from sqlalchemy.exc import IntegrityError
import bcrypt, random
from app.models.Usuario import Usuario
from app.models.TipoDocumento import TipoDocumento
from app.routes.usuario_routes import send_mail
from app.routes.votacion_routes import generar_sancion

bp = Blueprint("auth", __name__)


@bp.route("/", methods=["GET"])
def view_login():
    tiposDocumento = TipoDocumento.query.all()
    return render_template("auth/login.html", tiposDocumento=tiposDocumento)


@bp.route("/Register", methods=["GET"])
def view_register():
    tiposDocumento = TipoDocumento.query.all()
    return render_template("auth/register.html", tiposDocumento=tiposDocumento)


@bp.route("/verificar-usuario")
def view_verify_user():
    return render_template("auth/verificar-usuario.html")


@bp.route("/Verificar-codigo/<int:u>/<string:c>", methods=["GET"])
def view_verificar_codigo(u, c):
    return render_template("auth/verificar-codigo.html", idUsuario=u, correoOculto=c)


@bp.route("/registrar", methods=["GET", "POST"])
def register():
    if request.method == "POST":
        nombreUsuario = request.form["nombreUsuario"]  #
        apellidoUsuario = request.form["apellidoUsuario"]  #
        tipoDocumentoUsuario = request.form["tipoDocumentoUsuario"]  #
        documentoUsuario = request.form["documentoUsuario"]  #
        correoUsuario = request.form["correoUsuario"]  #
        telefonoUsuario = request.form["telefonoUsuario"]  #
        contraseniaUsuario = request.form["contraseniaUsuario"]  #
        contraseniaUsuario_confirm = request.form["contraseniaUsuario_confirm"]

        usuario = {
            "nombreUsuario": nombreUsuario,
            "apellidoUsuario": apellidoUsuario,
            "tipoDocumentoUsuario": tipoDocumentoUsuario,
            "documentoUsuario": documentoUsuario,
            "correoUsuario": correoUsuario,
            "telefonoUsuario": telefonoUsuario,
        }

        try:
            new_usuario = Usuario(
                nombreUsuario=nombreUsuario,
                apellidoUsuario=apellidoUsuario,
                idTipoDocumento=tipoDocumentoUsuario,
                documentoUsuario=documentoUsuario,
                correoUsuario=correoUsuario,
                telefonoUsuario=telefonoUsuario,
                contraseniaUsuario=bcrypt.hashpw(
                    contraseniaUsuario.encode("utf-8"), bcrypt.gensalt()
                ),
            )

            if len(contraseniaUsuario) < 8:
                flash(usuario, "usuarioOld")
                error = [
                    "contraseniaUsuario",
                    "La contraseña debe tener mínimo 8 caracteres",
                ]
                flash(error, "session")
                return redirect(url_for("auth.view_register"))

            if contraseniaUsuario != contraseniaUsuario_confirm:
                flash(usuario, "usuarioOld")
                return redirect(url_for("auth.view_register"))

            db.session.add(new_usuario)
            db.session.commit()
        except IntegrityError as ex:
            db.session.rollback()
            columna = columnaDuplicada(ex.orig)

            inputName = columna.split("U")[0]
            error = f"El {inputName} no está disponible"

            flash(usuario, "usuarioOld")
            error = [columna, error]
            flash(error, "session")
            return redirect(url_for("auth.view_register"))

        flash(["informacion", "Cuenta creada con exito"], "session")
        return redirect(url_for("auth.view_login"))

    return redirect(url_for("auth.view_register"))


@bp.route("/Login", methods=["POST", "GET"])
def login():
    if request.method == "POST":
        tipoDocumentoUsuario = request.form["tipoDocumentoUsuario"]
        documentoUsuario = request.form["documentoUsuario"]
        contraseniaUsuario = request.form["contraseniaUsuario"]

        usuario = Usuario.query.filter_by(
            idTipoDocumento=tipoDocumentoUsuario, documentoUsuario=documentoUsuario
        ).first()

        if usuario:
            if bcrypt.checkpw(
                hashed_password=usuario.contraseniaUsuario,
                password=contraseniaUsuario.encode("utf-8"),
            ):
                login_user(usuario)

                flash(
                    ["informacion", f"Bienvenido/a {current_user.nombreUsuario}"],
                    "session",
                )

                rs = (
                    current_user.rolUsuario.idRol == 3
                    or current_user.rolUsuario.idRol == 4
                )

                if rs:
                    return redirect(url_for("administrador.view_home"))
                return redirect(url_for("usuario.view_home"))

        flash(["error", "Las credenciales no coinciden"], "session")
        return redirect(url_for("auth.view_login"))

    return redirect(url_for("auth.view_login"))


@bp.route("/Logout", methods=["GET"])
@login_required
def logout():
    logout_user()
    flash(["informacion", "Tu sesión ha sido cerrada"], "session")
    return redirect(url_for("auth.login"))


@bp.route("/send/code", methods=["POST"])
def send_code():
    correoUsuario = request.form["correoUsuario"]

    usuario = Usuario.query.filter_by(correoUsuario=correoUsuario).first()

    if not usuario:
        flash(["error", "No encontramos tu correo, revisalo."], "session")
        return redirect(url_for("auth.view_verify_user"))

    codigo = gen_codigo(8)
    usuario.codigoUsuario = codigo

    db.session.commit()
    correoCodigo = render_template("componentes/correoCodigo.html", codigo=codigo)
    rs = send_mail(
        asunto="Código de verificación de usuario",
        contenido=correoCodigo,
        destinatario=correoUsuario,
        tipoContenido="html",
        finalMensaje="el código a tu correo",
    )

    if rs["rs"] == 500:
        flash(["error", f"{rs.msj}"], "session")
        return redirect(url_for("auth.view_verify_user"))

    return redirect(
        url_for(
            "auth.view_verificar_codigo",
            u=usuario.idUsuario,
            c=get_correo_oculto(usuario.correoUsuario),
        )
    )
    return render_template(
        "auth/verificar-codigo.html",
        usuario=usuario,
        correoOculto=get_correo_oculto(usuario.correoUsuario),
    )


@bp.route("/Verificar/Codigo/<int:usuario>", methods=["POST"])
def verificar_codigo(usuario):
    usuario = Usuario.query.get_or_404(usuario)
    codigoUsuario = request.form["codigoUsuario"]

    if not codigoUsuario == usuario.codigoUsuario:
        flash(
            ["error", "El código no coincide, verificalo y vuelve a intentarlo"],
            "session",
        )
        return render_template(
            "auth/verificar-codigo.html", idUsuario=usuario.idUsuario
        )

    return render_template("auth/reset-password.html", usuario=usuario)


# //////////////////////////////////////////////
# Funciones


def columnaDuplicada(exOrigin):
    return str(exOrigin).split("key")[-1].split(".")[-1].split("'")[0]


def gen_codigo(tamanio):
    mayus = "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
    digitos = "1234567890"
    opciones = [mayus, digitos]

    codigo = ""
    for _ in range(tamanio):
        opcion = random.choice(opciones)
        codigo += random.choice(opcion)

    return codigo


def get_correo_oculto(correo):
    correoOculto = ""
    correoDividido = correo.split("@")
    tamanio = len(correoDividido[0])

    for i, letra in enumerate(correoDividido[0]):
        if i > int(tamanio / 2):
            caracter = "*" if (tamanio - i) >= 2 else letra
            correoOculto += caracter

    correoOculto += "@"
    correoOculto += correoDividido[1]

    return correoOculto


# //////////////////////////////////////////////

app/routes/sancion_routes.py
from flask import (
    Blueprint,
    render_template,
    session,
    redirect,
    url_for,
    request,
    flash,
    jsonify,
)
from app.decorators.admin_required import admin_required
from app.decorators.owner_required import owner_required
from flask_login import login_required, current_user
from sqlalchemy import not_, asc
from app.models.Votacion import Votacion
from app.models.Usuario import Usuario
from app.models.Estado import Estado
from app.models.Sancion import Sancion
from app import db
import json
from app.routes.administrador_routes import carga_config


bp = Blueprint("sancion", __name__)


@bp.route("/Sanciones", methods=["POST", "GET"])
@login_required
@admin_required
@owner_required
def view_sanciones():
    usuarios = Usuario.query.filter(~Usuario.idRol.in_([3, 4])).all()
    sanciones = Sancion.query.order_by(Sancion.idSancion.desc()).all()
    config = carga_config()

    return render_template(
        "sanciones/index.html", usuarios=usuarios, sanciones=sanciones, config=config
    )


@bp.route("/buscar/sanciones", methods=["POST"])
def buscar_by_usuario():
    data = request.json

    documentoUsuario = data["documentoUsuario"]
    usuario = Usuario.query.filter_by(documentoUsuario=documentoUsuario).first()
    if not usuario:
        return {"rs": 404, "rz": "usuario"}

    sanciones = Sancion.query.filter_by(idUsuario=usuario.idUsuario).all()
    sanciones_dict = []
    for sancion in sanciones:
        sancion = {"idSancion": sancion.idSancion}
        sanciones_dict.append(sancion)

    if not sanciones:
        return {"rs": 404, "rz": "sancion"}

    return {"rs": 200, "sanciones": sanciones_dict}

app/routes/votacion_route.py
from flask import Blueprint, render_template, session, redirect, url_for, request, flash
from app.decorators.admin_required import admin_required
from flask_login import login_required, current_user
from sqlalchemy import not_, asc
from app.models.Votacion import Votacion
from app.models.Usuario import Usuario
from app.models.Estado import Estado
from sqlalchemy import func
from datetime import datetime
import pytz, os
from dotenv import load_dotenv
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
import smtplib
from app import db
from app.routes.usuario_routes import send_mail


bp = Blueprint("votacion", __name__)


@bp.route("/add/votes", methods=["POST"])
@admin_required
def add():
    if request.method == "POST":
        # correos = (
        #     Usuario.query.filter(Usuario.correoUsuario.isnot(None))
        #     .with_entities(Usuario.correoUsuario)
        #     .all()
        # )

        fechaInicio = datetime.now(pytz.utc)
        fechaFin = request.form["fechaFinVotacion"]

        new_votacion = Votacion(
            fechaInicioVotacion=fechaInicio,
            fechaFinVotacion=fechaFin,
        )

        db.session.add(new_votacion)
        db.session.query(Usuario).update({Usuario.idVoto: None})
        db.session.commit()

        ultimaVotacion = Votacion.query.order_by(asc(Votacion.idVotacion)).first()

        contenido = render_template("componentes/correoInicioVotaciones.html")

        rs = send_mail(
            asunto="Votaciones para representandes CGAO",
            contenido=contenido,
            destinatario=["cfmorales.diaz20@gmail.com"],
            finalMensaje="la información a los aprendices",
            tipoContenido="html",
        )

        flash(["informacion", "Votacion Iniciada"], "session")
        return redirect(url_for("administrador.view_votes"))


@bp.route("/Votes/Finish/<int:votacion>", methods=["POST"])
@admin_required
def finish_vote(votacion):
    rs = (
        db.session.query(Usuario.idVoto, func.count())
        .filter(Usuario.idVoto.isnot(None))
        .group_by(Usuario.idVoto)
        .order_by(func.count().desc())
        .first()
    )

    votacion = Votacion.query.get_or_404(votacion)
    totalVotos = (
        db.session.query(func.count(Usuario.idVoto))
        .filter(Usuario.idVoto.isnot(None))
        .scalar()
    )

    votacion.idEstado = 3

    if rs:
        usuario, votos = rs

        porcentaje = (votos / totalVotos) * 100
        votacion.ganadorVotacion = usuario
        votacion.cantVotosVotacion = votos
        votacion.totalVotosVotacion = totalVotos
        votacion.porcentajeVotosVotacion = porcentaje

    db.session.commit()

    flash(
        ["informacion", "La votacion se ha finalizado, ya puedes ver el ganador"],
        "session",
    )

    return redirect(url_for("administrador.view_votes"))


@bp.route("/Votes/Delete/<int:votacion>", methods=["POST"])
@admin_required
def delete_vote(votacion):
    votacion = Votacion.query.get_or_404(votacion)

    db.session.delete(votacion)
    db.session.commit()

    flash(
        ["informacion", "La votacion se ha eliminado"],
        "session",
    )

    return redirect(url_for("administrador.view_votes"))

app/templates/componentes/crear-votacion.html
<div id="ONuevaVotacion" class="o_nueva-votacion" show="false">
    <div id="NuevaVotacion" class="c_nueva-votacion" show="false">
        <header>
            <i id="CerrarNuevaVotacion" class="bi bi-x-lg"></i>
            <h2>Nueva votación</h2>
        </header>
        <div class="c_informacion">
            <p>Quieres iniciar una nueva votación?</p>
        </div>
        <form action="{{ url_for('votacion.add') }}" method="post">
            <div class="c_input fijo">
                <input
                    type="date"
                    name="fechaInicioVotacion"
                    id="FechaInicio"
                    readonly
                />
                <label for="FechaInicio">Inicio</label>
            </div>
            <div class="c_input fijo">
                <input
                    type="date"
                    name="fechaFinVotacion"
                    id="FechaFin"
                    required
                />
                <label for="FechaFin">Fin</label>
            </div>
            <div class="c_button">
                <button name="">Crear</button>
            </div>
        </form>
    </div>
</div>

app/templates/componentes/editarUsuario.html
<div class="o_editarUsuario" data-id="{{ usuario.idUsuario }}">
    <div class="c_editarUsuario">
        <div class="c_cerrar">
            <i class="bi bi-x-lg" data-name="cerrarEditarUsuario" data-id="{{ usuario.idUsuario }}"></i>
        </div>
        <div class="c_titulo">
            <h3>Usuario {{ usuario.nombreUsuario }}</h3>
        </div>
        <hr>
        <div class="c_form">
            <form action="{{ url_for('usuario.edit_user', usuario=usuario.idUsuario) }}" method="POST">

                <div class="c_input">
                    <input id="NombreUsuario" type="text" value="{{ usuario.nombreUsuario }}" placeholder="" required>
                    <label for="NombreUsuario">Nombre</label>
                </div>
                <div class="c_input">
                    <input id="ApellidoUsuario" type="text" value="{{ usuario.apellidoUsuario }}" placeholder=""
                        required>
                    <label for="ApellidoUsuario">Apellido</label>
                </div>
                <div class="c_select input-fijo">
                    <select name="tipoDocumentoUsuario">
                        <option selected value="{{ usuario.idTipoDocumento }}">{{
                            usuario.tipoDocumentoUsuario.descripcionTipoDocumento }}</option>
                        {% for tipoDocumento in tiposDocumento %}
                        {% if usuario.idTipoDocumento != tipoDocumento.idTipoDocumento %}
                        <option value="{{ tipoDocumento.idTipoDocumento }}">{{ tipoDocumento.descripcionTipoDocumento }}
                        </option>
                        {% endif %}
                        {% endfor %}
                    </select>
                    <label for="">Tipo de documento</label>
                </div>
                <div class="c_input">
                    <input id="DocumentoUsuario" type="text" value="{{ usuario.documentoUsuario }}" placeholder=""
                        required readonly>
                    <label for="DocumentoUsuario">Documento</label>
                </div>
                <div class="c_button">
                    <div class="c_buttons">
                        <button class="b_guardar">Guardar</button>
                        {% if usuario.idRol == 3 %}
                        <button formaction="{{ url_for('administrador.remove_admin', usuario=usuario.idUsuario) }}"
                            class="b_remover">Remover administrador</button>
                        {% elif usuario.idRol != 3 %}
                        <button formaction="{{ url_for('administrador.add_admin', usuario=usuario.idUsuario) }}"
                            class="hacer-admin">Hacer administrador</button>
                        {% endif %}
                    </div>
                    <div class="c_cancelar">
                        <button id="BTNcancelarEditar" class="b_cancelar" type="reset" data-name="cerrarEditarUsuario"
                            data-id="{{ usuario.idUsuario }}">cancelar</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>

app/templates/componentes/header-administrador.html
<link rel="stylesheet" href="{{ url_for('static', filename='css/icons/bootstrap-icons.css') }}" />
<link rel="stylesheet" href="{{ url_for('static', filename='css/header.css') }}" />
<script src="{{ url_for('static', filename='js/header.js') }}" defer></script>

<header id="header">
    <div class="c_logo">
        <a href="{{ url_for('administrador.view_home') }}">
            <img src="{{ url_for('static', filename='images/logo-SENA.png') }}" alt="Logo del SENA" />
        </a>
    </div>

    {% include 'componentes/links-administrador.html' %}
    <div class="c_menu-lateral">
        <div class="btn_menu-lateral">
            <div id="btn_menu" class="c_btn-menu">
                <span></span>
                <span></span>
                <span></span>
            </div>
        </div>
        <div id="menu-lateral" class="menu-lateral">
            <div class="c_usuario">
                <span>{{ current_user.rolUsuario.descripcionRol }}</span>
                <h4>{{ current_user.nombreUsuario }}</h4>
            </div>
            <span class="separador"></span>
            <div class="c_menu-movil">
                {% include 'componentes/links-administrador.html' %}
            </div>
            <span class="separador"></span>
            <div class="c_acciones-usuario">
                <ul>
                    <li>
                        <a href="{{ url_for('usuario.view_profile') }}">Perfil</a>
                    </li>
                    <li>
                        <a href="{{ url_for('auth.logout') }}">Cerrar sesión</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</header>


<div class="o_crearCandidato">
    <div class="c_addCandidato">
        <header>
            <i id="BTNCerrar" class="bi bi-x-lg"></i>
            <h2>Nuevo candidato</h2>
        </header>
        <form id="FormAgragarCandidato" action="#" method="POST" autocomplete="off">
            <div class="aprendiz">
                <div class="c_input">
                    <input type="text" id="DocumentoAprendiz" list="Aprendices" placeholder="">
                    <label for="DocumentoAprendiz">Documento aprendiz</label>
                    <div class="c_loading">
                        <img src="{{ url_for('static', filename='images/loading.gif') }}" alt="Loading">
                    </div>
                </div>
                <div class="c_choose">
                    <button id="BuscarAprendiz" type="button">Elegir</button>
                </div>
            </div>
            <div id="InformacionAprendiz" class="informacionAprendiz">
                <div class="c_estado">
                    <p>El aprendiz <span id="NombreAprendiz"></span> es <span class="tag" id="Valido"></span> para ser
                        candidato.
                    </p>
                </div>
                <div class="datos">
                    <div class="c_titulo">
                        <h4>Requisitos</h4>
                    </div>
                    <div class="c_tgs">
                        <span class="tag rol">Aprendiz</span>
                        <span class="tag foto">Foto</span>
                        <span class="tag descripcion">Descripción</span>
                        <span class="tag estado"></span>
                    </div>
                </div>
                <div class="c_button">
                    <button id="BTNAceptar" class="aceptar" disabled>Aceptar</button>
                    <button id="BTNCerrar" class="cancelar">Cancelar</button>
                </div>
            </div>
        </form>
        <datalist id="Aprendices">
            {% for usuario in usuarios %}
            <option value="{{ usuario.documentoUsuario }}"></option>
            {% endfor %}
        </datalist>

    </div>
</div>

<div id="O_configuraciones" class="o_configuraciones">
    <div class="c_configuraciones">
        <div class="c_cerrar">
            <i id="Cerrar-config" class="bi bi-x-lg"></i>
        </div>
        <header>
            <h2>Configuraciones</h2>
        </header>

        <div class="main">
            <form action="{{ url_for('administrador.edit_config') }}" method="post">
                <h3>Enviar correos</h3>
                <div class="row">
                    <label for="flexSwitcghCheckDefault">Inicio de la votación</label>
                    <label class="switch">
                        <input type="checkbox" id="flexSwitchCheckDefault" name="correosInicioVotacion" {{ 'checked' if
                            config.correosInicioVotacion else '' }}>
                        <span class="slider"></span>
                        slider"></span>
                    </label>
                </div>
                <div class="row">
                    <label class="form-check-label" for="flexSwitchCheckDefault">Fin de la votación</label>
                    <label class="switch">
                        <input type="checkbox" id="flexSwitchCheckDefault" name="correosFinVotacion" {{ 'checked' if
                            config.correosFinVotacion else '' }}>
                        <span class="slider"></span>
                    </label>
                </div>
                <div class="row">
                    <label class="form-check-label" for="flexSwitchCheckDefault">Sanciones</label>
                    <label class="switch">
                        <input type="checkbox" id="flexSwitchCheckDefault" name="correosSancionesVotacion" {{ 'checked'
                            if config.correosSancionesVotacion else '' }}>
                        <span class="slider"></span>
                    </label>
                </div>

                <div class="c_button">
                    <button id="reset" type="reset" style="display: none; visibility: hidden;">Reset</button>
                    <button>Guardar</button>
                </div>
            </form>
        </div>
    </div>
</div>

app/templates/componentes/header.html
<link rel="stylesheet" href="{{ url_for('static', filename='css/header.css') }}">
<script src="{{ url_for('static', filename='js/header.js') }}" defer></script>

<header id="header">
    <div class="c_logo">
        <a href="{{ url_for('usuario.view_home') }}">
            <img
                src="{{ url_for('static', filename='images/logo-SENA.png') }}"
                alt="Logo del SENA"
            />
        </a>
    </div>

    {% include 'componentes/links.html' %}
    <div class="c_menu-lateral">
        <div class="btn_menu-lateral">
            <div id="btn_menu" class="c_btn-menu">
                <span></span>
                <span></span>
                <span></span>
            </div>
        </div>
        <div id="menu-lateral" class="menu-lateral">
            <div class="c_usuario">
                <span>{{ current_user.rolUsuario.descripcionRol }}</span>
                <h4>{{ current_user.nombreUsuario }}</h4>
            </div>
            <span class="separador"></span>
            <div class="c_menu-movil">
                {% include 'componentes/links.html' %}
            </div>
            <span class="separador"></span>
            <div class="c_acciones-usuario">
                <ul>
                    <li>
                        <a href="{{ url_for('usuario.view_profile') }}">Perfil</a>
                        <!-- <span></span> -->
                    </li>
                    <li>
                        <a href="{{ url_for('auth.logout') }}">Cerrar sesión</a>
                        <!-- <span></span> -->
                    </li>
                </ul>
            </div>
        </div>
    </div>
</header>

app/templates/componentes/links-administrador.html
<nav>
    <ul>
        <li>
            <a href="{{ url_for('usuario.view_home') }}" target="_blank">Ver como aprendiz</a>
            <span></span>
        </li>
        <li>
            <a class="{{ 'active' if url_for('administrador.view_votes') == request.path else '' }}"
                href="{{ url_for('administrador.view_votes') }}">Votaciones</a>
            <span></span>
        </li>
        <li>
            <a id="Candidatos" href="#">Candidatos</a>
            <span></span>
        </li>
        <li>
            <a class="{{ 'active' if url_for('administrador.view_aprendices') == request.path else '' }}"
                href="{{ url_for('administrador.view_aprendices') }}">Aprendices</a>
            <span></span>
        </li>
        <li>
            <a href="{{ url_for('sancion.view_sanciones') }}">Sanciones</a>
            <span></span>
        </li>
        {% if current_user.idRol == 4 %}
        <li class="li-more">

            {% set is_in_max = True if url_for('administrador.view_votes') == request.path else False %}

            <a id="More" href="#">Más</a>
            <span></span>
            <div class="c_dropDown">
                <div id="DropDown" class="dropDown">
                    <ul>
                        <li>
                            <a href="{{ url_for('administrador.view_usuarios') }}">Usuarios</a>
                            <span></span>
                        </li>
                        <li>
                            <a href="{{ url_for('administrador.view_complementos') }}">Complementos</a>
                            <span></span>
                        </li>

                        <li>
                            <a id="Configuraciones" href="">Configuraciones</a>
                            <span></span>
                        </li>
                    </ul>
                </div>
            </div>
        </li>
        {% endif %}
    </ul>
</nav>